//File Generated By TelemetryFromXTCE.py

#include "LOBEpTelemetryContainer.h"

int LOBEpTelemetryContainer::size()
{
    return LOBEp_CONTAINER_SIZE;
}

unsigned char* LOBEpTelemetryContainer::getArray()
{
    return &telemetry[0];
}

char LOBEpTelemetryContainer::getStatus()
{
    return telemetry[0];
}
void LOBEpTelemetryContainer::setStatus(char uchar)
{
    telemetry[0] = uchar;
}
char LOBEpTelemetryContainer::getBootCounter()
{
    return telemetry[1];
}
void LOBEpTelemetryContainer::setBootCounter(char uchar)
{
    telemetry[1] = uchar;
}
long LOBEpTelemetryContainer::getResetCause()
{
    unsigned long ulong;
    ((unsigned char *)&ulong)[2] = telemetry[2];
    ((unsigned char *)&ulong)[1] = telemetry[3];
    ((unsigned char *)&ulong)[0] = telemetry[4];
    return ulong;
}
void LOBEpTelemetryContainer::setResetCause(long ulong)
{
    telemetry[2] = ((unsigned char *)&ulong)[2];
    telemetry[3] = ((unsigned char *)&ulong)[1];
    telemetry[4] = ((unsigned char *)&ulong)[0];
}
unsigned long LOBEpTelemetryContainer::getUptime()
{
    unsigned long ulong;
    ((unsigned char *)&ulong)[3] = telemetry[5];
    ((unsigned char *)&ulong)[2] = telemetry[6];
    ((unsigned char *)&ulong)[1] = telemetry[7];
    ((unsigned char *)&ulong)[0] = telemetry[8];
    return ulong;
}
void LOBEpTelemetryContainer::setUptime(unsigned long ulong)
{
    telemetry[5] = ((unsigned char *)&ulong)[3];
    telemetry[6] = ((unsigned char *)&ulong)[2];
    telemetry[7] = ((unsigned char *)&ulong)[1];
    telemetry[8] = ((unsigned char *)&ulong)[0];
}
unsigned long LOBEpTelemetryContainer::getTotalUptime()
{
    unsigned long ulong;
    ((unsigned char *)&ulong)[3] = telemetry[9];
    ((unsigned char *)&ulong)[2] = telemetry[10];
    ((unsigned char *)&ulong)[1] = telemetry[11];
    ((unsigned char *)&ulong)[0] = telemetry[12];
    return ulong;
}
void LOBEpTelemetryContainer::setTotalUptime(unsigned long ulong)
{
    telemetry[9] = ((unsigned char *)&ulong)[3];
    telemetry[10] = ((unsigned char *)&ulong)[2];
    telemetry[11] = ((unsigned char *)&ulong)[1];
    telemetry[12] = ((unsigned char *)&ulong)[0];
}
char LOBEpTelemetryContainer::getVersionNumber()
{
    return telemetry[13];
}
void LOBEpTelemetryContainer::setVersionNumber(char uchar)
{
    telemetry[13] = uchar;
}
short LOBEpTelemetryContainer::getMCUTemp()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[14];
    ((unsigned char *)&ushort)[0] = telemetry[15];
    return ushort;
}
void LOBEpTelemetryContainer::setMCUTemp(short ushort)
{
    telemetry[14] = ((unsigned char *)&ushort)[1];
    telemetry[15] = ((unsigned char *)&ushort)[0];
}
bool LOBEpTelemetryContainer::getINAStatus()
{
    return ((telemetry[16] & 0x80) != 0);
}
void LOBEpTelemetryContainer::setINAStatus(bool bval)
{
    telemetry[16] &= (~0x80);
    telemetry[16] |= bval ? 0x80 : 0x00;
}
bool LOBEpTelemetryContainer::getTMPStatus()
{
    return ((telemetry[16] & 0x40) != 0);
}
void LOBEpTelemetryContainer::setTMPStatus(bool bval)
{
    telemetry[16] &= (~0x40);
    telemetry[16] |= bval ? 0x40 : 0x00;
}
bool LOBEpTelemetryContainer::getTransmitINAStatus()
{
    return ((telemetry[16] & 0x20) != 0);
}
void LOBEpTelemetryContainer::setTransmitINAStatus(bool bval)
{
    telemetry[16] &= (~0x20);
    telemetry[16] |= bval ? 0x20 : 0x00;
}
bool LOBEpTelemetryContainer::getAmplifierINAStatus()
{
    return ((telemetry[16] & 0x10) != 0);
}
void LOBEpTelemetryContainer::setAmplifierINAStatus(bool bval)
{
    telemetry[16] &= (~0x10);
    telemetry[16] |= bval ? 0x10 : 0x00;
}
bool LOBEpTelemetryContainer::getPhasingTMPStatus()
{
    return ((telemetry[16] & 0x08) != 0);
}
void LOBEpTelemetryContainer::setPhasingTMPStatus(bool bval)
{
    telemetry[16] &= (~0x08);
    telemetry[16] |= bval ? 0x08 : 0x00;
}
bool LOBEpTelemetryContainer::getAmplifierTMPStatus()
{
    return ((telemetry[16] & 0x04) != 0);
}
void LOBEpTelemetryContainer::setAmplifierTMPStatus(bool bval)
{
    telemetry[16] &= (~0x04);
    telemetry[16] |= bval ? 0x04 : 0x00;
}
short LOBEpTelemetryContainer::getVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[17];
    ((unsigned char *)&ushort)[0] = telemetry[18];
    return ushort;
}
void LOBEpTelemetryContainer::setVoltage(short ushort)
{
    telemetry[17] = ((unsigned char *)&ushort)[1];
    telemetry[18] = ((unsigned char *)&ushort)[0];
}
short LOBEpTelemetryContainer::getCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[19];
    ((unsigned char *)&ushort)[0] = telemetry[20];
    return ushort;
}
void LOBEpTelemetryContainer::setCurrent(short ushort)
{
    telemetry[19] = ((unsigned char *)&ushort)[1];
    telemetry[20] = ((unsigned char *)&ushort)[0];
}
short LOBEpTelemetryContainer::getTemperature()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[21];
    ((unsigned char *)&ushort)[0] = telemetry[22];
    return ushort;
}
void LOBEpTelemetryContainer::setTemperature(short ushort)
{
    telemetry[21] = ((unsigned char *)&ushort)[1];
    telemetry[22] = ((unsigned char *)&ushort)[0];
}
short LOBEpTelemetryContainer::getReceiverRSSI()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[23];
    ((unsigned char *)&ushort)[0] = telemetry[24];
    return ushort;
}
void LOBEpTelemetryContainer::setReceiverRSSI(short ushort)
{
    telemetry[23] = ((unsigned char *)&ushort)[1];
    telemetry[24] = ((unsigned char *)&ushort)[0];
}
short LOBEpTelemetryContainer::getTransmitVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[25];
    ((unsigned char *)&ushort)[0] = telemetry[26];
    return ushort;
}
void LOBEpTelemetryContainer::setTransmitVoltage(short ushort)
{
    telemetry[25] = ((unsigned char *)&ushort)[1];
    telemetry[26] = ((unsigned char *)&ushort)[0];
}
short LOBEpTelemetryContainer::getTransmitCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[27];
    ((unsigned char *)&ushort)[0] = telemetry[28];
    return ushort;
}
void LOBEpTelemetryContainer::setTransmitCurrent(short ushort)
{
    telemetry[27] = ((unsigned char *)&ushort)[1];
    telemetry[28] = ((unsigned char *)&ushort)[0];
}
short LOBEpTelemetryContainer::getAmplifierVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[29];
    ((unsigned char *)&ushort)[0] = telemetry[30];
    return ushort;
}
void LOBEpTelemetryContainer::setAmplifierVoltage(short ushort)
{
    telemetry[29] = ((unsigned char *)&ushort)[1];
    telemetry[30] = ((unsigned char *)&ushort)[0];
}
short LOBEpTelemetryContainer::getAmplifierCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[31];
    ((unsigned char *)&ushort)[0] = telemetry[32];
    return ushort;
}
void LOBEpTelemetryContainer::setAmplifierCurrent(short ushort)
{
    telemetry[31] = ((unsigned char *)&ushort)[1];
    telemetry[32] = ((unsigned char *)&ushort)[0];
}
short LOBEpTelemetryContainer::getPhasingTemperature()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[33];
    ((unsigned char *)&ushort)[0] = telemetry[34];
    return ushort;
}
void LOBEpTelemetryContainer::setPhasingTemperature(short ushort)
{
    telemetry[33] = ((unsigned char *)&ushort)[1];
    telemetry[34] = ((unsigned char *)&ushort)[0];
}
short LOBEpTelemetryContainer::getAmplifierTemperature()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[35];
    ((unsigned char *)&ushort)[0] = telemetry[36];
    return ushort;
}
void LOBEpTelemetryContainer::setAmplifierTemperature(short ushort)
{
    telemetry[35] = ((unsigned char *)&ushort)[1];
    telemetry[36] = ((unsigned char *)&ushort)[0];
}
